
name: print  hello.txt
on: 
  push:
    branches:
      - main
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository to git
        uses: action/checkout@v3

      - name: Display hello.txt
        run: cat hello.txt
